/**
 * Row shapes for the Supabase schema.
 *
 * These are declared as standalone interfaces rather than generated by
 * `supabase gen types`, on purpose: a generated file cannot exist until a real
 * project exists, and a hand-written self-referential `Database` object type is
 * easy to get subtly wrong. Once the project is created, replace this file with
 * `npx supabase gen types typescript --project-id <ref>`.
 *
 * Money fields are always integer cents on the wire. The `_cents` naming is
 * deliberate: it makes an accidental float operation easy to spot.
 *
 * The generated columns (`in_stock`, `low_stock`, `is_on_sale`,
 * `discount_percent`) mirror the Python properties on the old Django `Product`
 * model, so both databases present the same catalogue.
 */

export interface CategoryRow {
  id: string
  name: string
  slug: string
  description: string | null
  icon: string | null
  sort_order: number
  is_active: boolean
  created_at: string
  /** Only present on categories_with_counts. */
  product_count?: number
}

export interface BrandRow {
  id: string
  name: string
  slug: string
  blurb: string | null
  created_at: string
  /** Only present on brands_with_counts. */
  product_count?: number
}

export interface ProductRow {
  id: string
  sku: string
  name: string
  slug: string
  category_id: string | null
  brand_id: string | null

  /** Integer cents, e.g. 249900 = R 2 499.00 */
  price_cents: number
  /** Struck-through "was" price. Null when not on sale. */
  compare_at_cents: number | null

  stock: number
  low_stock_threshold: number
  short_description: string | null
  description: string | null
  specs: Record<string, string>
  image_path: string | null
  rating: number
  rating_count: number
  condition: string
  is_featured: boolean
  is_active: boolean
  created_at: string
  updated_at: string

  /* Generated columns, computed by PostgreSQL. */
  in_stock: boolean
  low_stock: boolean
  is_on_sale: boolean
  discount_percent: number
}

export interface PromoCodeRow {
  id: string
  code: string
  percent_off: number
  description: string | null
  is_active: boolean
  valid_until: string | null
  created_at: string
}

type Relation = { name: string; slug: string }

/** A product row plus the embedded category/brand objects from the select. */
export interface ProductWithRelations extends ProductRow {
  category: Relation | Relation[] | null
  brand: Relation | Relation[] | null
}

/** A product flattened for display, with the joins resolved to strings. */
export interface CatalogProduct extends ProductRow {
  category: string | null
  category_slug: string | null
  brand: string | null
  brand_slug: string | null
}

/**
 * Turn a `ProductWithRelations` row into a flat `CatalogProduct`.
 *
 * Supabase returns an embedded relation as an array even when the relationship
 * resolves to a single row, so both shapes are handled here.
 */
export function toCatalogProduct(row: ProductWithRelations): CatalogProduct {
  const category = Array.isArray(row.category) ? row.category[0] : row.category
  const brand = Array.isArray(row.brand) ? row.brand[0] : row.brand

  const { category: _category, brand: _brand, ...product } = row

  return {
    ...product,
    category: category?.name ?? null,
    category_slug: category?.slug ?? null,
    brand: brand?.name ?? null,
    brand_slug: brand?.slug ?? null,
  }
}
